Config.UseWebhooks = true

Config.Webhooks = {
    ['addVehicleNote'] = {
        webhook = "",
        title = "Operation: Add vehicle note",
        description = "Player ID **[%s]** added note to vehicle %s | %s\nDescription %s",
        color = "16601088",
    },
    ['addCitizenNote'] = {
        webhook = "",
        title = "Operation: Add citizen note",
        description = "Player ID **[%s]** added note to citizen %s\nDescription %s",
        color = "16601088",
    },
    ['submitFine'] = {
        webhook = "",
        title = "Operation: Submit fine",
        description = "Player ID **[%s]** received money for issuing a fine %s",
        color = "16601088",
    },
    ['codeCommand'] = {
        webhook = "",
        title = "Operation: Command /code",
        description = "Player ID **[%s]** used the /code command and set the threat level to %s",
        color = "16601088",
    },
    ['setPWC'] = {
        webhook = "",
        title = "Operation: Set PWC",
        description = "Player ID **[%s]** assumed the role of Patrol Watch Commander",
        color = "16601088",
    },
    ['setAPWC'] = {
        webhook = "",
        title = "Operation: Set APWC",
        description = "Player ID **[%s]** assumed the role of Assistant of Patrol Watch Commander",
        color = "16601088",
    },
    ['setStatus'] = {
        webhook = "",
        title = "Operation: Set status",
        description = "Player ID **[%s]** change own status to [%s]",
        color = "16601088",
    },
    ['clearDispatch'] = {
        webhook = "",
        title = "Operation: Clear dispatch",
        description = "Player ID **[%s]** cleared dispatch",
        color = "16601088",
    },
    ['changePatrolStatus'] = {
        webhook = "",
        title = "Operation: Change patrol status",
        description = "Player ID **[%s]** change own patrol status to %s",
        color = "16601088",
    },
    ['removeAnn'] = {
        webhook = "",
        title = "Operation: Removed annoucement",
        description = "Player ID **[%s]** removed annoucement",
        color = "16601088",
    },
    ['addAnn'] = {
        webhook = "",
        title = "Operation: Added annoucement",
        description = "Player ID **[%s]** added annoucement",
        color = "16601088",
    },
    ['kickFromDuty'] = {
        webhook = "",
        title = "Operation: Kick from duty",
        description = "Player ID **[%s]** kicked from duty officer %s %s",
        color = "16601088",
    },
    ['addHouseNote'] = {
        webhook = "",
        title = "Operation: Removed house note",
        description = "Player ID **[%s]** removed house note",
        color = "16601088",
    },
    ['removeHouseNote'] = {
        webhook = "",
        title = "Operation: Added house note",
        description = "Player ID **[%s]** added house note",
        color = "16601088",
    },
    ['saveWarrant'] = {
        webhook = "",
        title = "Operation: Save warrant",
        description = "Player ID **[%s]** saved new warrant with title %s",
        color = "16601088",
    },
    ['saveEvidence'] = {
        webhook = "",
        title = "Operation: Save evidence",
        description = "Player ID **[%s]** saved new evidence with title %s",
        color = "16601088",
    },
    ['saveSettings'] = {
        webhook = "",
        title = "Operation: Save settings",
        description = "Player ID **[%s]** saved new settings [%s, %s, %s, %s, %s, %s]",
        color = "16601088",
    },
    ['deleteVehicleNote'] = {
        webhook = "",
        title = "Operation: Delete vehicle note",
        description = "Player ID **[%s]** deleted vehicle [%s] note",
        color = "16601088",
    },
    ['deleteCitizenNote'] = {
        webhook = "",
        title = "Operation: Delete citizen note",
        description = "Player ID **[%s]** deleted citizen note",
        color = "16601088",
    },
    ['addNote'] = {
        webhook = "",
        title = "Operation: Add note",
        description = "Player ID **[%s]** added new note",
        color = "16601088",
    },
    ['deleteNote'] = {
        webhook = "",
        title = "Operation: Delete note",
        description = "Player ID **[%s]** deleted note",
        color = "16601088",
    },
    ['editPatrol'] = {
        webhook = "",
        title = "Operation: Edit patrol",
        description = "Player ID **[%s]** edited patrol",
        color = "16601088",
    },
    ['createPatrol'] = {
        webhook = "",
        title = "Operation: Create patrol",
        description = "Player ID **[%s]** created patrol",
        color = "16601088",
    },
    ['joinPatrol'] = {
        webhook = "",
        title = "Operation: Join patrol",
        description = "Player ID **[%s]** joined patrol",
        color = "16601088",
    },
    ['quitPatrol'] = {
        webhook = "",
        title = "Operation: Leave patrol",
        description = "Player ID **[%s]** leaved patrol",
        color = "16601088",
    },
}