argento = {
        name = 'Argento',
        brand = 'Ubermacht',
        model = 'argento',
        price = 77694,
        category = 'sedans',
        hash = `argento`,
    },
asteropers = {
        name = 'Asterope RS',
        brand = 'Karin',
        model = 'asteropers',
        price = 77694,
        category = 'sedans',
        hash = `asteropers`,
    },
auroras2 = {
        name = 'Progen',
        brand = 'Aurora',
        model = 'auroras2',
        price = 77694,
        category = 'super',
        hash = `auroras2`,
    },