argento = {
        name = 'Argento',
        brand = 'Ubermacht',
        model = 'argento',
        price = 77694,
        category = 'sedans',
        hash = `argento`,
    },
asteropers = {
        name = 'Asterope RS',
        brand = 'Karin',
        model = 'asteropers',
        price = 77694,
        category = 'sedans',
        hash = `asteropers`,
    },
auroras2 = {
        name = 'Progen',
        brand = 'Aurora',
        model = 'auroras2',
        price = 77694,
        category = 'super',
        hash = `auroras2`,
    },
Bati901 = {
        name = 'Bati901',
        brand = 'Pegassi',
        model = 'bati901',
        price = 10000,
        category = 'motorcycle',
        hash = `bati901`,
    },
Bcat = {
        name = 'Bcat',
        brand = 'Vapid',
        model = 'bcat',
        price = 77694,
        category = 'offroad',
        hash = `bcat`,
    },
Bfd = {
        name = 'bfd',
        brand = 'declasse',
        model = 'bfd',
        price = 77694,
        category = 'suv',
        hash = `bfd`,
    },
Boorbc = {
        name = 'Boorbc',
        brand = 'Boor',
        model = 'boorbc',
        price = 77694,
        category = 'offroad',
        hash = `boorbc`,
    },
Brisket = {
        name = 'Brisket',
        brand = 'Weeny',
        model = 'brisket',
        price = 77694,
        category = 'classic',
        hash = `brisket`,
    },
Brisket2 = {
        name = 'Brisket2',
        brand = 'Weeny',
        model = 'brisket2',
        price = 77694,
        category = 'classic',
        hash = `brisket2`,
    },
Brisket3 = {
        name = 'Brisket3',
        brand = 'Weeny',
        model = 'brisket3',
        price = 77694,
        category = 'classic',
        hash = `brisket3`,
    },
Buffalosxumk = {
        name = 'Buffalosxp',
        brand = 'Bravado',
        model = 'buffalosxumk',
        price = 77694,
        category = 'sedan',
        hash = `buffalosxumk`,
    },
CaraCara = {
        name = 'CaraCara6x6',
        brand = 'Vapid',
        model = 'caracara6x6',
        price = 77694,
        category = 'truck',
        hash = `caracara6x6`,
    },
Comet6scw = {
        name = 'Comet6scw',
        brand = 'Phister',
        model = 'comet6scw',
        price = 77694,
        category = 'super',
        hash = `comet6scw ` ,
    },
Cometrr = {
        name = 'Cometrr',
        brand = 'Phister',
        model = 'cometrr',
        price = 77694,
        category = 'super',
        hash = `cometrr`,
    },
Contenderc = {
        name = 'Contenderc',
        brand = 'Vapid',
        model = 'contenderc',
        price = 77694,
        category = 'truck',
        hash = `contenderc`,
    },
Coqvice = {
        name = 'Coqvice',
        brand = 'Inverto',
        model = 'coqvice',
        price = 77694,
        category = 'sport',
        hash = `coqvice`,
    },
Cyphart = {
        name = 'Cyphart',
        brand = 'Ubermacht',
        model = 'cyphart',
        price = 77694,
        category = 'sport',
        hash = `cyphart`,
    },
Deimos = {
        name = 'Deimos',
        brand = 'Grotti',
        model = 'deimos',
        price = 77694,
        category = 'sedan',
        hash = `deimos`,
    },
Deluxowb = {
        name = 'Deluxowb',
        brand = 'Imponte',
        model = 'deluxowb',
        price = 77694,
        category = 'sedan',
        hash = `deluxowb`,
    },
Draftgpr = {
        name = 'Draftgpr',
        brand = 'Obey',
        model = 'draftgpr',
        price = 77694,
        category = 'sport',
        hash = `draftgpr`,
    },
Elegyheritage = {
        name = 'Elegyheritage',
        brand = 'Annis',
        model = 'elegyheritage',
        price = 77694,
        category = 'super',
        hash = `elegyheritage`,
    },
Elegyrace = {
        name = 'Elegyrace',
        brand = 'Bravado',
        model = 'elegyrace',
        price = 77694,
        category = 'super',
        hash = `elegyrace`,
    },
Fagaloac = {
        name = 'Fagaloac',
        brand = 'Vulcar',
        model = 'fagaloac',
        price = 77694,
        category = 'classic',
        hash = `fagaloac`,
    },
Furiawb = {
        name = 'Furiawb',
        brand = 'Grotti',
        model = 'furiawb',
        price = 77694,
        category = 'super',
        hash = `furiawb`,
    },
Gresleyh = {
        name = 'Gresleyh',
        brand = 'Bravado',
        model = 'gresleyh',
        price = 77694,
        category = 'suv',
        hash = `gresleyh`,
    },
Gstyosemite = {
        name = 'Gstyosemite',
        brand = 'Declasse',
        model = 'gstyosemite',
        price = 77694,
        category = 'truck',
        hash = `gstyosemite`,
    },
Gtsghell1 = {
        name = 'Gtsghell1',
        brand = 'Bravado',
        model = 'gtsghell1',
        price = 77694,
        category = 'sport',
        hash = `gtsghell1`,
    },
Hlbash = {
        name = 'Hlbash',
        brand = 'Bravado',
        model = 'hlbash',
        price = 77694,
        category = 'sport',
        hash = `hlbash`,
    },
Imperial = {
        name = 'Imperial',
        brand = 'Benefactor',
        model = 'imperial',
        price = 77694,
        category = 'van',
        hash = `imperial`,
    },
Jackgpr = {
        name = 'Jackgpr',
        brand = 'Ocelot',
        model = 'jackgpr',
        price = 77694,
        category = 'sedan',
        hash = `jackgpr`,
    },