argento = {
        name = 'Argento',
        brand = 'Ubermacht',
        model = 'argento',
        price = 77694,
        category = 'sedans',
        hash = `argento`,
    },
asteropers = {
        name = 'Asterope RS',
        brand = 'Karin',
        model = 'asteropers',
        price = 77694,
        category = 'sedans',
        hash = `asteropers`,
    },
auroras2 = {
        name = 'Progen',
        brand = 'Aurora',
        model = 'auroras2',
        price = 77694,
        category = 'super',
        hash = `auroras2`,
    },
Bati901 = {
        name = 'Bati901',
        brand = 'Pegassi',
        model = 'bati901',
        price = 10000,
        category = 'motorcycle',
        hash = `bati901`,
    },
Bcat = {
        name = 'Bcat',
        brand = 'Vapid',
        model = 'bcat',
        price = 77694,
        category = 'offroad',
        hash = `bcat`,
    },
Bfd = {
        name = 'bfd',
        brand = 'declasse',
        model = 'bfd',
        price = 77694,
        category = 'suv',
        hash = `bfd`,
    },
Boorbc = {
        name = 'Boorbc',
        brand = 'Boor',
        model = 'boorbc',
        price = 77694,
        category = 'offroad',
        hash = `boorbc`,
    },
Brisket = {
        name = 'Brisket',
        brand = 'Weeny',
        model = 'brisket',
        price = 77694,
        category = 'classic',
        hash = `brisket`,
    },
Brisket2 = {
        name = 'Brisket2',
        brand = 'Weeny',
        model = 'brisket2',
        price = 77694,
        category = 'classic',
        hash = `brisket2`,
    },
Brisket3 = {
        name = 'Brisket3',
        brand = 'Weeny',
        model = 'brisket3',
        price = 77694,
        category = 'classic',
        hash = `brisket3`,
    },
Buffalosxumk = {
        name = 'Buffalosxp',
        brand = 'Bravado',
        model = 'buffalosxumk',
        price = 77694,
        category = 'sedan',
        hash = `buffalosxumk`,
    },
CaraCara = {
        name = 'CaraCara6x6',
        brand = 'Vapid',
        model = 'caracara6x6',
        price = 77694,
        category = 'truck',
        hash = `caracara6x6`,
    },
Comet6scw = {
        name = 'Comet6scw',
        brand = 'Phister',
        model = 'comet6scw',
        price = 77694,
        category = 'super',
        hash = `comet6scw ` ,
    },
Cometrr = {
        name = 'Cometrr',
        brand = 'Phister',
        model = 'cometrr',
        price = 77694,
        category = 'super',
        hash = `cometrr`,
    },
Contenderc = {
        name = 'Contenderc',
        brand = 'Vapid',
        model = 'contenderc',
        price = 77694,
        category = 'truck',
        hash = `contenderc`,
    },
Coqvice = {
        name = 'Coqvice',
        brand = 'Inverto',
        model = 'coqvice',
        price = 77694,
        category = 'sport',
        hash = `coqvice`,
    },
Cyphart = {
        name = 'Cyphart',
        brand = 'Ubermacht',
        model = 'cyphart',
        price = 77694,
        category = 'sport',
        hash = `cyphart`,
    },
Deimos = {
        name = 'Deimos',
        brand = 'Grotti',
        model = 'deimos',
        price = 77694,
        category = 'sedan',
        hash = `deimos`,
    },
Deluxowb = {
        name = 'Deluxowb',
        brand = 'Imponte',
        model = 'deluxowb',
        price = 77694,
        category = 'sedan',
        hash = `deluxowb`,
    },
Draftgpr = {
        name = 'Draftgpr',
        brand = 'Obey',
        model = 'draftgpr',
        price = 77694,
        category = 'sport',
        hash = `draftgpr`,
    },
Elegyheritage = {
        name = 'Elegyheritage',
        brand = 'Annis',
        model = 'elegyheritage',
        price = 77694,
        category = 'super',
        hash = `elegyheritage`,
    },
Elegyrace = {
        name = 'Elegyrace',
        brand = 'Bravado',
        model = 'elegyrace',
        price = 77694,
        category = 'super',
        hash = `elegyrace`,
    },
Fagaloac = {
        name = 'Fagaloac',
        brand = 'Vulcar',
        model = 'fagaloac',
        price = 77694,
        category = 'classic',
        hash = `fagaloac`,
    },
Furiawb = {
        name = 'Furiawb',
        brand = 'Grotti',
        model = 'furiawb',
        price = 77694,
        category = 'super',
        hash = `furiawb`,
    },
Gresleyh = {
        name = 'Gresleyh',
        brand = 'Bravado',
        model = 'gresleyh',
        price = 77694,
        category = 'suv',
        hash = `gresleyh`,
    },
Gstyosemite = {
        name = 'Gstyosemite',
        brand = 'Declasse',
        model = 'gstyosemite',
        price = 77694,
        category = 'truck',
        hash = `gstyosemite`,
    },
Gtsghell1 = {
        name = 'Gtsghell1',
        brand = 'Bravado',
        model = 'gtsghell1',
        price = 77694,
        category = 'sport',
        hash = `gtsghell1`,
    },
Hlbash = {
        name = 'Hlbash',
        brand = 'Bravado',
        model = 'hlbash',
        price = 77694,
        category = 'sport',
        hash = `hlbash`,
    },
Imperial = {
        name = 'Imperial',
        brand = 'Benefactor',
        model = 'imperial',
        price = 77694,
        category = 'van',
        hash = `imperial`,
    },
Jackgpr = {
        name = 'Jackgpr',
        brand = 'Ocelot',
        model = 'jackgpr',
        price = 77694,
        category = 'sport',
        hash = `jackgpr`,
    },
Jogger = {
        name = 'Jogger',
        brand = 'Benefactor',
        model = 'jogger',
        price = 77694,
        category = 'sedan',
        hash = `jogger`,
    },
Komodafr = {
        name = 'Komodafr',
        brand = 'Lampadati',
        model = 'komodafr',
        price = 77694,
        category = 'sport',
        hash = `komodafr`,
    },
L35s = {
        name = 'L35s',
        brand = 'declasse',
        model = 'l35s',
        price = 77694,
        category = 'truck',
        hash = `l35s`,
    },
Lynxgpr = {
        name = 'Lynxgpr',
        brand = 'Bravado',
        model = 'lynxgpr',
        price = 77694,
        category = 'super',
        hash = `lynxgpr`,
    },
Mesaxl = {
        name = 'Mesaxl',
        brand = 'Canis',
        model = 'mesaxl',
        price = 77694,
        category = 'truck',
        hash = `mesaxl`,
    },
Molecule = {
        name = 'Molecule',
        brand = 'Maxwell',
        model = 'molecule',
        price = 77694,
        category = 'sport',
        hash = `molecule`,
    },
Morningstar = {
        name = 'Morningstar',
        brand = 'Schyster',
        model = 'morningstar',
        price = 77694,
        category = 'sedan',
        hash = `morningstar`,
    },
Cavalcade = {
        name = 'Cavalcade',
        brand = 'Albany',
        model = 'ncavalcade',
        price = 77694,
        category = 'suv',
        hash = `ncavalcade`,
    },
Nerops = {
        name = 'Nerops',
        brand = 'Truffade',
        model = 'nerops',
        price = 77694,
        category = 'super',
        hash = `nerops`,
    },
Nexus = {
        name = 'Nexus',
        brand = 'Dinka',
        model = 'nexus',
        price = 77694,
        category = 'sport',
        hash = `nexus`,
    },
Nkcruiser = {
        name = 'Nkcruiser',
        brand = 'nkcruiser',
        model = 'nkcruiser',
        price = 77694,
        category = 'emergency',
        hash = `nkcruiser`,
    },
Nsandstorm = {
        name = 'Nsandstorm',
        brand = 'Bravado',
        model = 'nsandstorm',
        price = 77694,
        category = 'truck',
        hash = `nsandstorm`,
    },
Nspeedo = {
        name = 'Nspeedo',
        brand = 'Vapid',
        model = 'nspeedo',
        price = 77694,
        category = 'van',
        hash = `nspeedo`,
    },
Paragonxr = {
        name = 'Paragonxr',
        brand = 'Enus',
        model = 'paragonxr',
        price = 77694,
        category = 'super',
        hash = `paragonxr`,
    },
PDalamo2 = {
        name = 'PDalamo2',
        brand = 'Declasse',
        model = 'pdalamo2',
        price = 77694,
        category = 'emergency',
        hash = `pdalamo2`,
    },
polcoq4 = {
        name = 'polcoq4',
        brand = 'Inverto',
        model = 'polcoq2',
        price = 77694,
        category = 'emergency',
        hash = `polcoq2`,
    },
Policeb = {
        name = 'Policeb',
        brand = 'Shitzu',
        model = 'policeb',
        price = 77694,
        category = 'emergency',
        hash = `policeb`,
    },
Policebikerb = {
        name = 'Policebikerb',
        brand = 'Maibatsu',
        model = 'buffalosxumk',
        price = 77694,
        category = 'sedan',
        hash = `buffalosxumk`,
    },
Polvstr = {
        name = 'Polvstr',
        brand = 'Albany',
        model = 'polvstr',
        price = 77694,
        category = 'emergency',
        hash = `polvstr`,
    },
R300w = {
        name = 'R300w',
        brand = 'Annis',
        model = 'r300w',
        price = 77694,
        category = 'sport',
        hash = `r300w`,
    },
Remustwo = {
        name = 'Remustwo',
        brand = 'Annis',
        model = 'emustwo',
        price = 77694,
        category = 'sedan',
        hash = `remustwo`,
    },
RevolutionS = {
        name = 'RevolutionS',
        brand = 'Karin',
        model = 'revolutions',
        price = 77694,
        category = 'sport',
        hash = `revolutions`,
    },
RH4 = {
        name = 'RH4',
        brand = 'Annis',
        model = 'rh4',
        price = 77694,
        category = 'sport',
        hash = `rh4`,
    },
RH82 = {
        name = 'RH82',
        brand = 'Annis',
        model = 'rh82',
        price = 77694,
        category = 'sport',
        hash = `rh82`,
    },
Roxanne = {
        name = 'Roxanne',
        brand = 'Annis',
        model = 'roxanne',
        price = 77694,
        category = 'Sport',
        hash = `roxanne`,
    },
sandbulance = {
        name = 'sandbulance',
        brand = 'Vapid',
        model = 'sandbulance',
        price = 77694,
        category = 'emergency',
        hash = `sandbulance`,
    },
Scheisser = {
        name = 'Scheisser',
        brand = 'Benefactor',
        model = 'scheisser',
        price = 77694,
        category = 'sedan',
        hash = `scheisser`,
    },
Schlagenstr = {
        name = 'Schlagenstr',
        brand = 'Benefactor',
        model = 'schlagenstr',
        price = 77694,
        category = 'super',
        hash = `schlagenstr`,
    },
Schwarzer2 = {
        name = 'Schwarzer2',
        brand = 'Benefactor',
        model = 'schwarzer2',
        price = 77694,
        category = 'sport',
        hash = `schwarzer2`,
    },
Sentigpr = {
        name = 'Sentigpr',
        brand = 'Ubermacht',
        model = 'sentigpr',
        price = 77694,
        category = 'sport',
        hash = `sentigpr`,
    },
Sentinelsg4 = {
        name = 'Sentinelsg4',
        brand = 'Ubermacht',
        model = 'sentinelsg4',
        price = 77694,
        category = 'sedan',
        hash = `sentinelsg4`,
    },
Stiron = {
        name = 'Stiron',
        brand = 'Lightbee',
        model = 'stiron',
        price = 77694,
        category = 'motorcycle',
        hash = `stiron`,
    },
Stratumc = {
        name = 'Stratumc',
        brand = 'Stratum',
        model = 'stratum',
        price = 77694,
        category = 'sedan',
        hash = `stratum`,
    },
Sultan2c = {
        name = 'Sultan2c',
        brand = 'Karin',
        model = 'sultan2c',
        price = 77694,
        category = 'sedan',
        hash = `sultan2c`,
    },
Sunrise1 = {
        name = 'Sunrise1',
        brand = 'Maibatsu',
        model = 'sunrise1',
        price = 77694,
        category = 'sedan',
        hash = `sunrise1`,
    },
Superkart = {
        name = 'Superkart',
        brand = 'Nagaski',
        model = 'superkart',
        price = 77694,
        category = 'sport',
        hash = `superkart`,
    },
Tampar = {
        name = 'Tampar',
        brand = 'Karin',
        model = 'tampar',
        price = 77694,
        category = 'classic',
        hash = `tampar`,
    },
Taranis = {
        name = 'Taranis',
        brand = 'Coil',
        model = 'taranis',
        price = 77694,
        category = 'sedan',
        hash = `taranis`,
    },
Tempestafr = {
        name = 'Tempestafr',
        brand = 'Pegassi',
        model = 'tempestafr',
        price = 77694,
        category = 'super',
        hash = `tempestafr`,
    },
Torrence = {
        name = 'Torrence',
        brand = 'Vapid',
        model = 'torrence',
        price = 77694,
        category = 'sedan',
        hash = `torrence`,
    },
Umkalamo = {
        name = 'Umkalamo',
        brand = 'Vapid',
        model = 'umkalamo',
        price = 77694,
        category = 'suv',
        hash = `umkalamo`,
    },
Vigerozxwb = {
        name = 'Vigerozxwb',
        brand = 'Declasse',
        model = 'vigerozxwb',
        price = 77694,
        category = 'sport',
        hash = `vigerozxwb`,
    },
Vigout = {
        name = 'Vigout',
        brand = 'Declasse',
        model = 'vigout',
        price = 77694,
        category = 'offroad',
        hash = `vigout`,
    },
Warrenerwb = {
        name = 'Warrenerwb',
        brand = 'Vulcar',
        model = 'warrenerwb',
        price = 77694,
        category = 'classic',
        hash = `warrenerwb`,
    },
Zrgpr = {
        name = 'Zrgpr',
        brand = 'Annis',
        model = 'zrgpr',
        price = 77694,
        category = 'sport',
        hash = `zrgpr`,
    },