INSERT INTO `items` (`name`, `label`, `limit`) VALUES
	('crafting_table', 'Crafting Table', 100),
	('drug_table', 'Drug Table', 100),
	('blueprint_pistol', 'Pistol Blueprint', 100),
	('wheat', 'Wheat', 100),
	('wheat_raw', 'Raw Wheat', 100),
	('tomato', 'Tomato', 100),
	('tomato_raw', 'Raw Tomato', 100),
	('broccoli', 'Broccoli', 100),
	('broccoli_raw', 'Raw Broccoli', 100),
	('corn', 'Corn', 100),
	('burger', 'Burger', 100),
	('bread', 'Bread', 100),
	('meat', 'Meat', 100),
	('chips', 'Chips', 100),
	('potato', 'Potato', 100),
	('salad', 'Salad', 100),
	('lettuce', 'Lettuce', 100),
	('soda', 'Soda', 100),
	('sugar', 'Sugar', 100),
	('iron', 'Iron', 100),
	('metal_pipe', 'Metal Pipe', 100),
	('wood', 'Wood', 100),
	('cocaine_raw', 'Unprocessed Cocaine', 100),
	('cocaine', 'Cocaine', 100),
	('weed_raw', 'Unprocessed Weed', 100),
	('weed', 'Weed', 100),
	('heroin_raw', 'Unprocessed Heroin', 100),
	('heroin', 'Heroin', 1)
;