name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sync to S3 Bucket
        run: |
          aws s3 sync ./ s3://solus-server-resources/files/[dwtesting]/dw_lootcrate --delete

      - name: Sync to R2
        run: |
          rclone sync ./ r2:solusassets/files/[dwtesting]/dw_lootcrate
